# Test this without rebuilding the docker image $> docker-compose up
# Test this with rebuilding the docker image $> docker-compose up --build

version: '3.7'

services:
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    image: raft-node:latest
    container_name: node1
    environment:
      - TERM=xterm
    working_dir: /csci251
    networks:
      - raft_protocol_network
    ports:
      - 6788
      - 6789
    command:
      - /bin/bash
      - -c
      - |
        echo "Node 1 started!"
        ./node-start.sh
        tail -f /dev/null

  node2:
    image: raft-node:latest
    container_name: node2
    depends_on:
      - node1
    environment:
      - TERM=xterm
    working_dir: /csci251
    networks:
      - raft_protocol_network
    ports:
      - 6788
      - 6789
    command:
      - /bin/bash
      - -c
      - |
        echo "Node 2 started!"
        ./node-start.sh
        tail -f /dev/null

  node3:
    image: raft-node:latest
    container_name: node3
    depends_on:
      - node2
    environment:
      - TERM=xterm
    working_dir: /csci251
    networks:
      - raft_protocol_network
    ports:
      - 6788
      - 6789
    command:
      - /bin/bash
      - -c
      - |
        echo "Node 3 started!"
        ./node-start.sh
        tail -f /dev/null

  node4:
    image: raft-node:latest
    container_name: node4
    depends_on:
      - node3
    environment:
      - TERM=xterm
    working_dir: /csci251
    networks:
      - raft_protocol_network
    ports:
      - 6788
      - 6789
    command:
      - /bin/bash
      - -c
      - |
        echo "Node 4 started!"
        ./node-start.sh
        tail -f /dev/null

  node5:
    image: raft-node:latest
    container_name: node5
    depends_on:
      - node4
    environment:
      - TERM=xterm
    working_dir: /csci251
    networks:
      - raft_protocol_network
    ports:
      - 6788
      - 6789
    command:
      - /bin/bash
      - -c
      - |
        echo "Node 5 started!"
        ./node-start.sh
        tail -f /dev/null


networks:
  raft_protocol_network: